### ISSUE TITLE
risesheet exceeded quota in local storage

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-google-sheet#13]
When pulling in data from a spreadsheet with approximately 4000 rows I receive in error saying "failed to execute setitem on storage risesheet exceeded quota".
We need to address local storage quota somehow.

http://www.screencast.com/t/p6AfhFygRJ

example spreadsheet: https://docs.google.com/spreadsheets/d/1fuUu85XePkt6hp62ydUW6oEFIrBxBA1OobCmTA0aDmo/edit#gid=0

**Comment by alanclayton** [comment]
@mmeiers @stulees was this issue resolved?

**Comment by mmeiers** [comment]
@alanclayton @stulees 

This was resolved some time ago.
