### ISSUE TITLE
"sheets" attribute not applying to localStorage

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-google-sheet#28]
When using the "sheets" attribute in <rise-google-sheets-> the value does not apply to local Storage.
http://www.screencast.com/t/a0W8K6kuM2

This is needed so we can do separate instances of the component in the same html file without creating conflicts in data. Currently using ID attribute still creates conflicts and each instance of the component pulls in the same data.

Conversation regarding bug in this pr: https://github.com/Rise-Vision/client-content-presentations/pull/56

**Comment by stulees** [comment]
@mmeiers This has been fixed with PR #29 , closing, thanks.
