### ISSUE TITLE
Demo file doesn't adhere to playlist duration.

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-google-sheet#8]
When I add the spreadsheet component with another component (demo component) inside a playlist the spreadsheet component showed up all the time regardless of what was specified as the playlist item duration.
http://www.screencast.com/t/iddULx355

I tried the exact same test with rss component earlier today and I didn't have that problem.
This appears to be an issue with the demo file vs the actual component.

**Comment by stulees** [comment]
@mmeiers FYI, closing as this was fixed in PR #9
